version: '2'
services:

    node1:
        image: gwlatest-1node_node1_centos
        links:
        - cassandra-m
        #volumes:
        #  Configuring volume for Node Manager conf (modified using API Gateway Manager web application)
        # -  node1_CONF_DATA:/opt/Axway/apigateway/conf
        #  Configuring volume for Node Manager trace (modified using API Gateway Manager web application)
        # -  node1_TRACE_DATA:/opt/Axway/apigateway/trace
        #  Configuring volume for Node Manager logs (includes Domain and Transaction logs modified using API Gateway Manager web application)
        # -  node1_LOGS_DATA:/opt/Axway/apigateway/logs
        #  Configuring volume for Node Manager events (modified using API Gateway Manager web application)
        # -  node1_EVENTS_DATA:/opt/Axway/apigateway/events
        #  Configuring volume for API Gateway Group Configuration, data, logging and trace.
        # -  node1_GROUP_DATA:/opt/Axway/apigateway/groups
        #  Configuring volume for API Gateway user data eg. ActiveMQ, File-based filters, Ehcache etc
        # -  node1_USER_DATA:/custom_path/to/userdata/
        hostname: node1
        ports:
        - 8090:8090
        - 8075:8075
        - 8081:8081
        - 8065:8065
        environment:
        - START_BACKOFF_SECS=60 # starts after Cassandra cluster and 60s after previous instance
        - CASSANDRA_HOSTS=cassandra-m
        - APIGW_LICENSE #To set the license run: export APIGW_LICENSE="$(cat /path/to/licenses/lic.lic | gzip | base64)" on the docker host
        privileged: true
        restart: on-failure:2


    cassandra-m:
        image: cassandra_centos
        environment:
        - START_BACKOFF_SECS=0 # prevents race between nodes joining the cluster
        - SEEDS=cassandra-m
        - MAX_HEAP_SIZE=1G
        - HEAP_NEWSIZE=400m
        #volumes:
        #  Cassandra data volume
        # -  cassandra-m_DATA:/opt/cassandra/data
        #  Cassandra logs volume
        # -  cassandra-m_LOGS:/opt/cassandra/logs
        hostname: cassandra-m
        restart: on-failure:2

